# https://docs.docker.com/compose/compose-file/compose-file-v3/
name: lucytech

networks:
  main: {}

services:
  client:
    container_name: qbank-client
    image: serendpty/edu-qbank-client-web:latest
    ports:
    - 3000:80
    networks:
    - main
    depends_on:
    - api
  api:
    container_name: qbank-api
    image: serendpty/edu-qbank-api:latest
    ports:
    - 8080:8080
    - 8081:8081
    networks:
    - main
    volumes:
    - ./api/configs:/opt/configs
    restart: always
