# https://docs.docker.com/compose/compose-file/compose-file-v3/
name: lucytech

networks:
  main: {}

services:
  clients:
    container_name: web-page-analyzer-clients-cdn
    image: kosatnkn/web-page-analyzer-clients-cdn:latest
    ports:
    - 3000:80
    networks:
    - main
    depends_on:
    - api
  api:
    container_name: web-page-analyzer-api
    image: kosatnkn/web-page-analyzer-api:latest
    ports:
    - 8000:8000
    - 8001:8001
    networks:
    - main
    volumes:
    - ./api/configs:/opt/configs
    restart: always
