# https://docs.docker.com/compose/compose-file/compose-file-v3/
name: lucytech

networks:
  main: {}

services:
  client:
    container_name: web-page-analyzer-client-cdn
    image: kosatnkn/web-page-analyzer-client-cdn:latest
    ports:
    - 3000:80
    networks:
    - main
    depends_on:
    - api
  api:
    container_name: web-page-analyzer-api
    image: kosatnkn/web-page-analyzer-api:latest
    ports:
    - 8080:8080
    - 8081:8081
    networks:
    - main
    volumes:
    - ./api/configs:/opt/configs
    restart: always
